import { Shift } from '../components/admin/ShiftSchedule';

const getDateOffset = (offset: number) => {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  return date.toISOString().split('T')[0];
};

export const sampleShifts: Shift[] = [
  // CN1 - This Week
  {
    id: '1',
    employeeId: '1',
    employeeName: 'Nguyễn Văn An',
    branch: 'CN1',
    date: getDateOffset(0),
    startTime: '06:00',
    endTime: '14:00',
    shiftType: 'morning',
  },
  {
    id: '2',
    employeeId: '2',
    employeeName: 'Trần Thị Bình',
    branch: 'CN1',
    date: getDateOffset(0),
    startTime: '08:00',
    endTime: '16:00',
    shiftType: 'morning',
  },
  {
    id: '3',
    employeeId: '4',
    employeeName: 'Phạm Thu Dung',
    branch: 'CN1',
    date: getDateOffset(0),
    startTime: '14:00',
    endTime: '22:00',
    shiftType: 'afternoon',
  },
  {
    id: '4',
    employeeId: '10',
    employeeName: 'Lý Thị Oanh',
    branch: 'CN1',
    date: getDateOffset(0),
    startTime: '16:00',
    endTime: '23:00',
    shiftType: 'afternoon',
  },
  {
    id: '5',
    employeeId: '1',
    employeeName: 'Nguyễn Văn An',
    branch: 'CN1',
    date: getDateOffset(1),
    startTime: '07:00',
    endTime: '15:00',
    shiftType: 'morning',
  },
  {
    id: '6',
    employeeId: '2',
    employeeName: 'Trần Thị Bình',
    branch: 'CN1',
    date: getDateOffset(1),
    startTime: '14:00',
    endTime: '22:00',
    shiftType: 'afternoon',
  },
  {
    id: '7',
    employeeId: '4',
    employeeName: 'Phạm Thu Dung',
    branch: 'CN1',
    date: getDateOffset(2),
    startTime: '06:00',
    endTime: '14:00',
    shiftType: 'morning',
  },
  {
    id: '8',
    employeeId: '10',
    employeeName: 'Lý Thị Oanh',
    branch: 'CN1',
    date: getDateOffset(2),
    startTime: '15:00',
    endTime: '23:00',
    shiftType: 'afternoon',
  },

  // CN2 - This Week
  {
    id: '9',
    employeeId: '3',
    employeeName: 'Lê Minh Cường',
    branch: 'CN2',
    date: getDateOffset(0),
    startTime: '06:00',
    endTime: '14:00',
    shiftType: 'morning',
  },
  {
    id: '10',
    employeeId: '5',
    employeeName: 'Hoàng Quốc Hùng',
    branch: 'CN2',
    date: getDateOffset(0),
    startTime: '09:00',
    endTime: '17:00',
    shiftType: 'morning',
  },
  {
    id: '11',
    employeeId: '7',
    employeeName: 'Đặng Văn Long',
    branch: 'CN2',
    date: getDateOffset(0),
    startTime: '14:00',
    endTime: '22:00',
    shiftType: 'afternoon',
  },
  {
    id: '12',
    employeeId: '12',
    employeeName: 'Đinh Thị Quỳnh',
    branch: 'CN2',
    date: getDateOffset(1),
    startTime: '07:00',
    endTime: '15:00',
    shiftType: 'morning',
  },
  {
    id: '13',
    employeeId: '3',
    employeeName: 'Lê Minh Cường',
    branch: 'CN2',
    date: getDateOffset(1),
    startTime: '15:00',
    endTime: '23:00',
    shiftType: 'afternoon',
  },

  // CN3 - This Week
  {
    id: '14',
    employeeId: '6',
    employeeName: 'Võ Thị Kim',
    branch: 'CN3',
    date: getDateOffset(0),
    startTime: '06:00',
    endTime: '14:00',
    shiftType: 'morning',
  },
  {
    id: '15',
    employeeId: '8',
    employeeName: 'Bùi Thị Mai',
    branch: 'CN3',
    date: getDateOffset(0),
    startTime: '08:00',
    endTime: '16:00',
    shiftType: 'morning',
  },
  {
    id: '16',
    employeeId: '11',
    employeeName: 'Trương Văn Phúc',
    branch: 'CN3',
    date: getDateOffset(0),
    startTime: '10:00',
    endTime: '18:00',
    shiftType: 'afternoon',
  },
  {
    id: '17',
    employeeId: '9',
    employeeName: 'Ngô Minh Nam',
    branch: 'CN3',
    date: getDateOffset(0),
    startTime: '14:00',
    endTime: '22:00',
    shiftType: 'afternoon',
  },
  {
    id: '18',
    employeeId: '6',
    employeeName: 'Võ Thị Kim',
    branch: 'CN3',
    date: getDateOffset(1),
    startTime: '07:00',
    endTime: '15:00',
    shiftType: 'morning',
  },
  {
    id: '19',
    employeeId: '9',
    employeeName: 'Ngô Minh Nam',
    branch: 'CN3',
    date: getDateOffset(1),
    startTime: '15:00',
    endTime: '23:00',
    shiftType: 'afternoon',
  },
  {
    id: '20',
    employeeId: '8',
    employeeName: 'Bùi Thị Mai',
    branch: 'CN3',
    date: getDateOffset(2),
    startTime: '06:00',
    endTime: '14:00',
    shiftType: 'morning',
  },
  {
    id: '21',
    employeeId: '11',
    employeeName: 'Trương Văn Phúc',
    branch: 'CN3',
    date: getDateOffset(2),
    startTime: '14:00',
    endTime: '22:00',
    shiftType: 'afternoon',
  },
];

export function initializeSampleShifts() {
  const existing = localStorage.getItem('shifts');
  if (!existing) {
    localStorage.setItem('shifts', JSON.stringify(sampleShifts));
  }
}
